apiVersion: v1
kind: Pod
metadata:
  name: wa-lanchonete
  labels:
    app: wa-lanchonete
spec:
  containers:
    - name: wa-lanchonete-container
      image: willmarques/wa-lanchonete_clean_api:latest
      ports:
        - containerPort: 3001
      envFrom:
        - configMapRef:
            name: wa-lanchonete-configmap